### ISSUE TITLE
shaarli 0.10.2 works fine... by writing and reading a corrupted datastore.php?

### ISSUE THREAD

**Issue by mfioretti** [shaarli/Shaarli#1222]
Hello,

I have installed shaarli 0.10.2 on php7/ubuntu 16.04 x86_64, and managed to import over 27k bookmars in it, using the method recently discussed at https://gitter.im/shaarli/Shaarli

After the import (and temporarily rising the memory limit of PHP..) shaarli seems to work perfectly... while using/generating a **CORRUPTED** datastore.php

Details: the software works. I can display bookmarks, filter them, add them with  the bookmarklet, edit, see the picwall... everything. And the only thing I see in the apache error log file is the occasional PHP Notice: 

"Undefined index: shorturl in /var/www/html/shaarli/tmp/linklist.b91ef64efc3688266305ea9b42e5017e.rtpl.php on line 282,...

BUT: this hack to export the shaarli bookmarks (which is essential for me)

php -r 'print(json_encode(unserialize(gzinflate(base64_decode(preg_replace("!.*/\* (.+) \*/.*!", "$1", file_get_contents("/var/www/html/shaarli/data/datastore.php")))))));'

**constantly** fails saying "PHP Warning:  gzinflate(): data error in Command line code on line 1", no matter what I set the length parameter of gzinflate (or gzdecode) to.

Indeed, if I copy datastore.php to another file, remove the php tags, convert it to a test.gz file with the base64 tool, gunzip says that that file is NOT a gzipped file. Ditto if I try with unzip.

How can it be possible that the **same** gzinflate function that is working perfectly when called from apache, always fails from the command line, on the same computer? 

Any clue to what is happening, and how to fix it?

thanks

**Comment by virtualtam** [comment]
Hi @mfioretti,

If Shaarli can handle its datastore properly, it is rather unlikely that it is corrupted. Also, directly editing this file is discouraged as it should be considered as an internal resource.

To ease understanding what's going on here (without spelunking through the Gitter chat history), and allow us to eventually provide a more elegant solution to users who might have similar needs, would you mind editing this issue with the following information?

- a description of the use case:
    - where do the bookmarks come from? (e.g. which service, which format, etc.)
    - which tool has been used to import the bookmarks to Shaarli?
    - do you plan to use Shaarli in conjunction with other software?
- which issues do/did you encounter? I seem to remember you had to increase Apache and PHP memory limits to handle a large bookmark dump

The proper solution, though, is to rely on the REST API which is the _only supported public interface_ to programmatically manage data. There are examples provided for a [variety of languages](https://shaarli.readthedocs.io/en/master/REST-API/#clients-and-examples) which should help getting started when addressing such specific situations. Plus, any improvement made to the API benefits all its users (vs. needle-in-a-haystack cases).

---

As per this specific issue, here's a first guess:

> ```shell
> php -r 'print(json_encode(unserialize(gzinflate(base64_decode(preg_replace("!./* (.+) */.!", "$1", file_get_contents("/var/www/html/shaarli/data/datastore.php")))))));'
> ```

This command seems invalid/outdated, especially the `preg_replace` arguments which do not match the example provided in the [Various hacks](https://shaarli.readthedocs.io/en/master/guides/various-hacks/) guide.

The proper command should be:

```shell
php -r 'print(json_encode(unserialize(gzinflate(base64_decode(preg_replace("!.*/\* (.+) \*/.*!", "$1", file_get_contents("data/datastore.php")))))));' | jq .
```

**Comment by mfioretti** [comment]
hello @virtualtam and thanks for your comment.

when I first asked how to import bookmarks, I could not properly configure a server to use the rest api, for reasons not relevant right now.

Tonight I could, with letsencrypt cert and all (except ntp, I will later). I installed shaarli v0.97.2 and v0.10.2 side by side, just to compare them.

Then I installed shaarli client with python 3.4, following the procedure described here, with pip and a virtualenv:

https://github.com/shaarli/python-shaarli-client/blob/master/docs/user/installation.rst

I sourced .virtualenvs/shaarli/bin/activate then created this .shaarli/shaarli.conf file:
[shaarli]
url = https://example.com (my real URL, of course)
secret = secret taken by shaarli config panel

Now if I run the shaarli client as specified here I get:

(shaarli) [marco@myserver ~]$ shaarli -c .shaarli/shaarli.conf post-link --url https://w3c.github.io/activitypub/
Traceback (most recent call last):
  File "/home/pilatort4/.virtualenvs/shaarli/bin/shaarli", line 11, in <module>
    sys.exit(main())
  File "/home/pilatort4/.virtualenvs/shaarli/lib64/python3.4/site-packages/shaarli_client/main.py", line 65, in main
    print(json.dumps(response.json(), sort_keys=True, indent=4))
  File "/home/pilatort4/.virtualenvs/shaarli/lib64/python3.4/site-packages/requests/models.py", line 896, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
(shaarli) [marco@myserver ~]$

**Comment by mfioretti** [comment]
I am sorry, I have realized only now that a more appropriate place for issues with the client (as it seems here) is probably this other page: https://github.com/shaarli/python-shaarli-client/issues/33

**Comment by mfioretti** [comment]
Answering the other questions by @virtualtam about the server:

"description of the use case:"

- where do the bookmarks come from? (e.g. which service, which format, etc.)

I have a .csv file. I used a Perl script to transform it into a JSON file with the same format of those generated by the "hack" described in the shaarli docs. Then I pass it to a php file tat is basically copied from the shaarli sources:

/usr/bin/php $json2shaarli JSONfile DATASTOREFILE.php
   
this is $json2shaarli (created with suggestion from the shaarli chat:
```
<?php
$database = file_get_contents($argv[1]); // load JSON dump of the database
$links = json_decode($database, true);
foreach ($links as &$link) {
    $link['created'] = DateTime::createFromFormat('Y-m-d H:i:s.u', $link['created']['date']);
    $link['updated'] = DateTime::createFromFormat('Y-m-d H:i:s.u', $link['updated']['date']);
}
file_put_contents($argv[2], '<?php /* '.base64_encode(gzdeflate(serialize($links))).' */ ?>' );
exit;
?>
```

- which tool has been used to import the bookmarks to Shaarli? **see above**
- do you plan to use Shaarli in conjunction with other software?

I was on semanticscuttle which is practically dead. I tried shiori, and as cute as it is is NOT for me, really. For **me** shaarli is almost perfect, really (but see "capacity" below)... except this fact that it doesn't store bookmarks in sqlite or mysql, which I could read and write at will with standard procedures.Personally, I do not only need a one-time import of many thousands of bookmarks, but I also need several times a week to add or read them (e.g. all the bookmarks with a specific **combination** of 2/3 tags) with scripts, to generate reports and other documents
(if I could fix this, and **also** get one or two extra text fields to each record... I would be in paradise, really)

- which issues do/did you encounter? I seem to remember you had to increase Apache and PHP memory limits to handle a large bookmark dump

the datastore I generated with the script above, suggested on the shaarli chat, would simply not run unless I increased the memory_limit a lot. So another question, as far as I am concerned is "does shaarli's datastore have some de-facto built-in maximum number of bookmarks that it can handle? (at least with the php memory limits usually found on hosting account, i.e. 128/256MB?

thanks.

**Comment by mfioretti** [comment]
last but not least: the first php code I used to get a json dump is the one I copied from the website hacks page, and successfully tested on my first test install. But also running the different version that you posted today:

php -r 'print(json_encode(unserialize(gzinflate(base64_decode(preg_replace("!.*/\* (.+) \*/.*!", "$1", file_get_contents("data/datastore.php")))))));' | jq .`

doesn't change anything. From the browser, shaarli runs without any problems. When I run your latest command, I still get the "gzinflate(): data error" message. So yes, even if the datastore I generated is not canonical, it is good enough to be read and written from the browser, it is not "unzippable" when using the same php functions from the command line, on the same machine

**Comment by virtualtam** [comment]
Hi @mfioretti, thanks for summing up your use cases, and the different issues you had with the datastore.

Shaarli should run fine with several thousand bookmarks, but if you are concerned with performance and memory limits, I would suggest taking one of those paths:
- hosting Shaarli with Nginx and PHP-FPM (real boost in comparison to Apache HTTPD + PHP module)
- hosting Shaarli using the Docker images (which come withNginx and PHP-FPM pre-configured)

I wrote a Netscape bookmark generator a while back to diagnose performance issues with the import feature, maybe it can be of use to check whether your instance (or another test instance hosted on the same server) can handle the load corresponding to your usage? The script can be found in our https://github.com/shaarli/devtools repository, it might be a bit rough so let me know if you have issues running it.

**Comment by mfioretti** [comment]
Hi @virtualtam , thanks for asking. After ~10 days of extensively using Shaarli, in my own, admittedly non-standard scenario, I can report that:

1) it is running, since my comment here of 9 days ago, with exactly the nginx + php-fpm configuration suggested in the shaarli docs, not with Apache+phpmodule

2) as of now, my instance has 26078 shaares, 7971 private, and it does abort every now and then. By "abort" I mean that the shaarli pop-up window goes blank and nothing happens ~15/20% of times I add a bookmark, or update it. Indeed, the server logs shows lots of lines like these:

PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 4198400 bytes) in /var/www/html/shaarli/vendor/slim/slim/Slim/Http/Response.php on line 349

if you want, I can parse the logs and provide you a summary of how those fatal errors are distributed, i.e. how many times it happens on each line of each php file. Or if you need other input, or want me to test tweaking the server, just ask. Personally, I would really like to explore roads different from "raise the memory limit". NOT for my own needs, but because I'd like to see shaarli become e.g. a plugin for owncloud, and in general something usable on as many web hosting accounts as possible, not just by people like me who can play almost at will with their own VPS.

**Comment by ArthurHoaro** [comment]
Due to how Shaarli store and read its data, it needs to load the whole datastore in the memory. There is no workaround this except with deep code rewriting. There might be some optimizations that can be done, but it won't change that if you have 100MB of data, it'll have to load 100MB of data.

Making Shaarli work with a proper RDBMS is something that we want to do, but won't come soon.

But you should definitely increase your memory limit to avoid hitting fatal errors.
