### ISSUE TITLE
0.10.2 - PHP exception thrown when adding link or editing existing items

### ISSUE THREAD

**Issue by waltkelly** [shaarli/Shaarli#1252]
I upgraded to 0.10.2 from 0.9.7 by 
```
$ mv Shaarli Shaarli-0.10.2-git
$ tar xvf shaarli-v0.10.2-full.tar.gz
$ rsync -av Shaarli-0.10.2-git/data Shaarli/data
$ cd Shaarli/
$ chgrp -R -v www-data cache data pagecache tmp
```
Visiting my updated Shaarli website, it seemed that the site worked to read, but adding or editing entries failed when clicking on the final "Apply" action, in that a blank page appeared, with the url of the modification transaction, e.g `http://menla.dhis.org/Shaarli/?post=https%3A%2F%2Fun-denial.com%2F2018%2F12%2F11%2Fby-tim-watkins-climbing-everest-in-high-heels-aka-its-the-overshoot-stupid%2F#` shown in the address bar, instead of e.g. `http://menla.dhis.org/Shaarli/?`

Looking in the webserver error log, I find:
```
2018-12-13 11:32:20: (mod_fastcgi.c.2543) FastCGI-stderr: Stack trace:
2018-12-13 11:32:20: (mod_fastcgi.c.2543) FastCGI-stderr: #0 ```
/home/parz/Shaarli/application/History.php(88): History->check()
2018-12-13 11:32:20: (mod_fastcgi.c.2543) FastCGI-stderr: #1 /home/parz/Shaarli/application/History.php(149): History->initialize()
2018-12-13 11:32:20: (mod_fastcgi.c.2543) FastCGI-stderr: #2 /home/parz/Shaarli/application/History.php(99): History->addEvent('CREATED', 494)
2018-12-13 11:32:20: (mod_fastcgi.c.2543) FastCGI-stderr: #3 /home/parz/Shaarli/index.php(1178): History->addLink(Array)
2018-12-13 11:32:20: (mod_fastcgi.c.2543) FastCGI-stderr: #4 /home/parz/Shaarli/index.php(1866): renderPage(Object(Shaarli\Config\ConfigManager), Object(PluginManager), Object(LinkDB), Object(History), Object(Shaarli\Security\SessionManager), Object(Shaarli\Security\LoginManager))
2018-12-13 11:32:20: (mod_fastcgi.c.2543) FastCGI-stderr: #5 {main}
2018-12-13 11:32:20: (mod_fastcgi.c.2543) FastCGI-stderr:   thrown in /home/parz/Shaarli/application/History.php on line 174
```

**Comment by virtualtam** [comment]
Closing due to lack of feedback, feel free to reopen.
