### ISSUE TITLE
401 error in api-interface on mobile devices

### ISSUE THREAD

**Issue by fsch0203** [shaarli/Shaarli#1448]
I am working on a web application (in the browser) that connects to my shaarli server (on the NAS) based on the shaarli-api-interface. The strange thing is that it all works great from my desktop computer, but mobile devices keep responding with "not authorized" (401 error). I have tried to include a different name for the user-agent in het http-header, but that makes no difference. Replacing fetch by axios is no solution either. Anyone an idea?

The javascript code looks like this. The generateToken is a function that generates the required token.

```javascript
function getShaarliData(what) {
    let url = local.url + 'api/v1/' + what;
    fetch(url, {
            headers: {
                "Content-Type": "application/json",
                "Authorization": "Bearer " + generateToken(local.secret)
            }
        })
        .then(response => response.json())
        .then((json) => {
            console.log(JSON.stringify(json));
            $('#response').html(JSON.stringify(json));
        })
        .catch((error) => {
            console.error('Error:', error);
            $('#error').html(JSON.stringify(json));
        });
}
```
Thanks, Frans

**Comment by ArthurHoaro** [comment]
Hi, sorry for the delay, your issue got buried.

You set `dev.debug` to true in your `data/config.json.php` file to get more information about 401 errors. It might be time related, as JWT tokens are only valid for a few minutes.

**Comment by nodiscc** [comment]
Same problem encountered in https://github.com/shaarli/python-shaarli-client/pull/52:

```json
$ shaarli get-info 
{
    "message": "Not authorized: Invalid JWT signature",
    "stacktrace": "Shaarli\\Api\\Exceptions\\ApiAuthorizationException: #0 /var/www/shaarli.EXAMPLE.org/application/api/ApiMiddleware.php(133): Shaarli\\Api\\ApiUtils::validateJwtToken('eeefffggghhh...', 'aaabbbcccddd')
#1 /var/www/shaarli.EXAMPLE.org/application/api/ApiMiddleware.php(99): Shaarli\\Api\\ApiMiddleware->checkToken(Object(Slim\\Http\\Request))
#2 /var/www/shaarli.EXAMPLE.org/application/api/ApiMiddleware.php(68): Shaarli\\Api\\ApiMiddleware->checkRequest(Object(Slim\\Http\\Request))
#3 [internal function]: Shaarli\\Api\\ApiMiddleware->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Slim\\Route))
#4 /var/www/shaarli.EXAMPLE.org/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Array, Array)
#5 [internal function]: Slim\\DeferredCallable->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Slim\\Route))
#6 /var/www/shaarli.EXAMPLE.org/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\\DeferredCallable), Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Object(Slim\\Route))
#7 /var/www/shaarli.EXAMPLE.org/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\\Route->Slim\\{closure}(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))
#8 /var/www/shaarli.EXAMPLE.org/vendor/slim/slim/Slim/Route.php(268): Slim\\Route->callMiddlewareStack(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))
#9 /var/www/shaarli.EXAMPLE.org/vendor/slim/slim/Slim/App.php(503): Slim\\Route->run(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))
#10 /var/www/shaarli.EXAMPLE.org/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\\App->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))
#11 /var/www/shaarli.EXAMPLE.org/vendor/slim/slim/Slim/App.php(392): Slim\\App->callMiddlewareStack(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))
#12 /var/www/shaarli.EXAMPLE.org/vendor/slim/slim/Slim/App.php(297): Slim\\App->process(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))
#13 /var/www/shaarli.EXAMPLE.org/index.php(176): Slim\\App->run(true)
#14 {main}"
```

**Comment by ArthurHoaro** [comment]
My Python installation is more or less broken, did you fix your issue? We didn't change anything in the API authentication process recently.

**Comment by nodiscc** [comment]
I will recheck

**Comment by nodiscc** [comment]
I can't reproduce it anymore after reinstalling https://github.com/shaarli/python-shaarli-client from master, shaarli v0.12.1, debian/apache/php-fpm.

@fsch0203 are you still getting this 401 error?

If yes, can you please enable [`dev.debug` in Shaarli's configuration file](https://shaarli.readthedocs.io/en/master/Shaarli-configuration/#configuration-file-example) and post the full error returned by the API?

Else I guess this issue can be closed.
