### ISSUE TITLE
Error: Call to undefined function Shaarli\Front\Controller\Admin\ctype_digit()

### ISSUE THREAD

**Issue by andreworg** [shaarli/Shaarli#1700]
I get this after clicking on the edit icon for an entry:

URL: https://mysite/bm/index.php/admin/shaare/<entry_number>
(n.b.: "bm" is the documentroot subfolder where the code is. currently running without URL rewriting.)

```
Call to undefined function Shaarli\Front\Controller\Admin\ctype_digit()
/var/www/localhost/htdocs/bm/application/front/controller/admin/ShaarePublishController.php76
#0 [internal function]: Shaarli\Front\Controller\Admin\ShaarePublishController->displayEditForm(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#1 /var/www/localhost/htdocs/bm/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#2 /var/www/localhost/htdocs/bm/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#3 /var/www/localhost/htdocs/bm/application/front/ShaarliMiddleware.php(55): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#4 /var/www/localhost/htdocs/bm/application/front/ShaarliAdminMiddleware.php(25): Shaarli\Front\ShaarliMiddleware->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#5 [internal function]: Shaarli\Front\ShaarliAdminMiddleware->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#6 /var/www/localhost/htdocs/bm/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Array, Array)
#7 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#8 /var/www/localhost/htdocs/bm/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#9 /var/www/localhost/htdocs/bm/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#10 /var/www/localhost/htdocs/bm/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#11 /var/www/localhost/htdocs/bm/vendor/slim/slim/Slim/App.php(503): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#12 /var/www/localhost/htdocs/bm/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#13 /var/www/localhost/htdocs/bm/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#14 /var/www/localhost/htdocs/bm/vendor/slim/slim/Slim/App.php(297): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#15 /var/www/localhost/htdocs/bm/index.php(176): Slim\App->run(true)
#16 {main}

```

**Comment by ArthurHoaro** [comment]
`ctype_digit` is part of `[ctype](https://www.php.net/manual/en/book.ctype.php)` extension. It's the first time I see a PHP installation without this extension buit-in. What's your OS?

**Comment by andreworg** [comment]
Silly me, I should have thought of that.
I was lead to thinking it was local to the software, because it is not included in the [list of required or optional extensions](https://shaarli.readthedocs.io/en/master/Server-configuration/) from the docs.
The OS is a tight custom-built Docker image, based on Alpine.

**Comment by ArthurHoaro** [comment]
No you're right, it should be added to our documentation.
It is actually included in our Docker image: https://github.com/shaarli/Shaarli/blob/master/Dockerfile#L36
