### ISSUE TITLE
Docker image latest; unable to create config file

### ISSUE THREAD

**Issue by nejcmenard** [shaarli/Shaarli#1799]
Hi.

i am trying to upgrade my shaarli v.0.9 to latest version due to datastore being empy every few months...

now i did try to load latest docker image, but after install page, the system respond with:
---

Error while writing config file after configuration update.

        Shaarli could not create the config file. Please make sure Shaarli has the right to write in the folder is it installed in. "data/config.json.php"
#0 /var/www/shaarli/application/config/ConfigManager.php(240): Shaarli\Config\ConfigJson->write('data/config.jso...', Array)
#1 /var/www/shaarli/application/front/controller/visitor/InstallController.php(152): Shaarli\Config\ConfigManager->write(false)
#2 [internal function]: Shaarli\Front\Controller\Visitor\InstallController->save(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#3 /var/www/shaarli/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#4 /var/www/shaarli/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#5 /var/www/shaarli/application/front/ShaarliMiddleware.php(55): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#6 [internal function]: Shaarli\Front\ShaarliMiddleware->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#7 /var/www/shaarli/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Array, Array)
#8 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#9 /var/www/shaarli/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#10 /var/www/shaarli/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#11 /var/www/shaarli/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#12 /var/www/shaarli/vendor/slim/slim/Slim/App.php(503): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#13 /var/www/shaarli/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#14 /var/www/shaarli/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#15 /var/www/shaarli/vendor/slim/slim/Slim/App.php(297): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#16 /var/www/shaarli/index.php(196): Slim\App->run(true)
#17 {main}
      ---

after changing manually permissions to 755, then the problem is 

---
An error occurred while parsing JSON configuration file (data/config.json.php): error code #4
➜ Syntax error
Please check your JSON syntax (without PHP comment tags) using a JSON lint tool such as jsonlint.com.
---

but the file is empty. umask problem? my docker knowledge is lacking...

thank you for any help...

**Comment by nejcmenard** [comment]
docker host had disk space issues (overlay2 folder). never mind.
