### ISSUE TITLE
Datastore corruption when the disk is full

### ISSUE THREAD

**Issue by siSSSou** [shaarli/Shaarli#1810]
The system drive went full (100%) this morning, and Shaarli is displaying this error instead of normal data :
```
An unexpected error happened, and the error template could not be displayed.

unserialize() expects parameter 1 to be string, bool given
/var/www/Shaarli/application/bookmark/BookmarkIO.php90
#0 /var/www/Shaarli/application/bookmark/BookmarkIO.php(90): unserialize(false)
#1 /var/www/Shaarli/application/bookmark/BookmarkFileService.php(71): Shaarli\Bookmark\BookmarkIO->read()
#2 /var/www/Shaarli/application/container/ContainerBuilder.php(97): Shaarli\Bookmark\BookmarkFileService->__construct(Object(Shaarli\Config\ConfigManager), Object(Shaarli\History), Object(malkusch\lock\mutex\FlockMutex), true)
#3 /var/www/Shaarli/vendor/pimple/pimple/src/Pimple/Container.php(118): Shaarli\Container\ContainerBuilder->Shaarli\Container\{closure}(Object(Shaarli\Container\ShaarliContainer))
#4 /var/www/Shaarli/vendor/slim/slim/Slim/Container.php(109): Pimple\Container->offsetGet('bookmarkService')
#5 /var/www/Shaarli/vendor/slim/slim/Slim/Container.php(164): Slim\Container->get('bookmarkService')
#6 /var/www/Shaarli/application/container/ContainerBuilder.php(110): Slim\Container->__get('bookmarkService')
#7 /var/www/Shaarli/vendor/pimple/pimple/src/Pimple/Container.php(118): Shaarli\Container\ContainerBuilder->Shaarli\Container\{closure}(Object(Shaarli\Container\ShaarliContainer))
#8 /var/www/Shaarli/vendor/slim/slim/Slim/Container.php(109): Pimple\Container->offsetGet('pageBuilder')
#9 /var/www/Shaarli/vendor/slim/slim/Slim/Container.php(164): Slim\Container->get('pageBuilder')
#10 /var/www/Shaarli/application/front/controller/visitor/ErrorController.php(20): Slim\Container->__get('pageBuilder')
#11 [internal function]: Shaarli\Front\Controller\Visitor\ErrorController->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(TypeError))
#12 /var/www/Shaarli/vendor/slim/slim/Slim/App.php(728): call_user_func_array(Object(Shaarli\Front\Controller\Visitor\ErrorController), Array)
#13 /var/www/Shaarli/vendor/slim/slim/Slim/App.php(396): Slim\App->handlePhpError(Object(TypeError), Object(Slim\Http\Request), Object(Slim\Http\Response))
#14 /var/www/Shaarli/vendor/slim/slim/Slim/App.php(297): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#15 /var/www/Shaarli/index.php(176): Slim\App->run(true)
#16 {main}
```
Using an older datastore.php I get normal behavior of the app.

I suppose that current datastore.php has been corrupted when the storage incident happened !
Is it possible to recover these data in datastore.php ?

NB : sadly I make daily bachups of mysql databases but not files... I know it's dumb ;-(

**Comment by nodiscc** [comment]
Hi,
known problem https://github.com/shaarli/Shaarli/issues?q=is%3Aissue+data+loss+is%3Aclosed, a full disk corrupts the datastore, but it's supposed to be fixed in https://github.com/shaarli/Shaarli/pull/1570 if I remember correctly... which Shaarli version are you using and how did you install it?

**Comment by siSSSou** [comment]
> Hi, known problem https://github.com/shaarli/Shaarli/issues?q=is%3Aissue+data+loss+is%3Aclosed, a full disk corrupts the datastore, but it's supposed to be fixed in #1570 if I remember correctly... which Shaarli version are you using and how did you install it?

I installed 0.12.1 from release ZIP.

But I re-installed it and set up a cron backup. 
I suppose my issue can be closed now ;-)

**Comment by nodiscc** [comment]
Leaving this open so I can recheck/try to reproduce datastore corruption when the disk is full.

**Comment by wolfskaempf** [comment]
@ArthurHoaro Thank you so much for fixing this, I really appreciate it!
