### ISSUE TITLE
Errors after upgrading from Shaarli 0.11.1 to 0.12.1 - php 7.4.15

### ISSUE THREAD

**Issue by MagicFab** [shaarli/Shaarli#1861]
I am following the [upgrade docs](https://shaarli.readthedocs.io/en/master/Upgrade-and-migration/#upgrading-from-zip-archives).

I tried upgrading from version 0.11.1 to 0.12.1 , running in shared hosting at Dreamhost on PHP 7.4.15 (default template, all plugins disabled), likeso:

* cp -R /home/myuser/my.domain.com/l/ /var/www/shaarli-backup/ 
* wget https://github.com/shaarli/Shaarli/releases/download/v0.12.0/shaarli-v0.12.0-full.zip
* unzip shaarli-v0.12.0-full.zip
* rsync -avP --delete Shaarli/ /home/myuser/my.domain.com/l/

At this point if I load the main page it asks for credentials setup as if this was a new install. If I complete the information, Shaarli then works but all bookmarks are lost.

However, If I don't load the main page and I recover the data backup from v0.11 ....

* rm -r /home/myuser/my.domain.com/l/data
* cp -R /var/www/shaarli-backup/data/ /home/myuser/my.domain.com/l/.

... I get a list of error messages :

```
An unexpected error happened, and the error template could not be displayed.

Return value of Shaarli\Bookmark\Bookmark::getId() must be of the type int or null, string returned
/home/myuser/my.domain.com/l/application/bookmark/Bookmark.php158
#0 /home/myuser/my.domain.com/l/application/bookmark/BookmarkArray.php(77): Shaarli\Bookmark\Bookmark->getId()
#1 /home/myuser/my.domain.com/l/application/legacy/LegacyUpdater.php(590): Shaarli\Bookmark\BookmarkArray->offsetSet('20180623_082929', Object(Shaarli\Bookmark\Bookmark))
#2 [internal function]: Shaarli\Legacy\LegacyUpdater->updateMethodMigrateDatabase()
#3 /home/myuser/my.domain.com/l/application/legacy/LegacyUpdater.php(118): ReflectionMethod->invoke(Object(Shaarli\Legacy\LegacyUpdater))
#4 /home/myuser/my.domain.com/l/application/bookmark/BookmarkFileService.php(417): Shaarli\Legacy\LegacyUpdater->update()
#5 /home/myuser/my.domain.com/l/application/bookmark/BookmarkFileService.php(86): Shaarli\Bookmark\BookmarkFileService->migrate()
#6 /home/myuser/my.domain.com/l/application/container/ContainerBuilder.php(97): Shaarli\Bookmark\BookmarkFileService->__construct(Object(Shaarli\Config\ConfigManager), Object(Shaarli\History), Object(malkusch\lock\mutex\FlockMutex), true)
#7 /home/myuser/my.domain.com/l/vendor/pimple/pimple/src/Pimple/Container.php(118): Shaarli\Container\ContainerBuilder->Shaarli\Container\{closure}(Object(Shaarli\Container\ShaarliContainer))
#8 /home/myuser/my.domain.com/l/vendor/slim/slim/Slim/Container.php(109): Pimple\Container->offsetGet('bookmarkService')
#9 /home/myuser/my.domain.com/l/vendor/slim/slim/Slim/Container.php(164): Slim\Container->get('bookmarkService')
#10 /home/myuser/my.domain.com/l/application/container/ContainerBuilder.php(110): Slim\Container->__get('bookmarkService')
#11 /home/myuser/my.domain.com/l/vendor/pimple/pimple/src/Pimple/Container.php(118): Shaarli\Container\ContainerBuilder->Shaarli\Container\{closure}(Object(Shaarli\Container\ShaarliContainer))
#12 /home/myuser/my.domain.com/l/vendor/slim/slim/Slim/Container.php(109): Pimple\Container->offsetGet('pageBuilder')
#13 /home/myuser/my.domain.com/l/vendor/slim/slim/Slim/Container.php(164): Slim\Container->get('pageBuilder')
#14 /home/myuser/my.domain.com/l/application/front/controller/visitor/ErrorController.php(20): Slim\Container->__get('pageBuilder')
#15 [internal function]: Shaarli\Front\Controller\Visitor\ErrorController->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(TypeError))
#16 /home/myuser/my.domain.com/l/vendor/slim/slim/Slim/App.php(728): call_user_func_array(Object(Shaarli\Front\Controller\Visitor\ErrorController), Array)
#17 /home/myuser/my.domain.com/l/vendor/slim/slim/Slim/App.php(396): Slim\App->handlePhpError(Object(TypeError), Object(Slim\Http\Request), Object(Slim\Http\Response))
#18 /home/myuser/my.domain.com/l/vendor/slim/slim/Slim/App.php(297): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#19 /home/myuser/my.domain.com/l/index.php(176): Slim\App->run(true)
#20 {main}
```

This worked for upgrading 0.97 -> 0.10 -> 0.10.1 -> 0.11 - > 0.11.1.

**Comment by MagicFab** [comment]
Workaround : 

1. Export all links as html using the default options
2. Install Shaarli 0.12.1 from scratch, don't copy data from older version
3. Use Shaarli import tool to import from the file created in 1)

**Comment by ArthurHoaro** [comment]
It looks like at least one of your link ID was not migrated properly during a previous upgrade. It could probably be debugged, but in these situations the workaround you mentioned is usually easier.
