### ISSUE TITLE
Searching by keyword and filtering by tags not working

### ISSUE THREAD

**Issue by ankitml** [shaarli/Shaarli#678]
Here is the stack trace

```
2016/10/28 16:39:46 [error] 42865#42865: *54 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function mb_convert_case() in /var/www/sharli/application/LinkFilter.php:351
Stack trace:
#0 /var/www/sharli/application/LinkFilter.php(253): LinkFilter::tagsStrToArray('ideas ', false)
#1 /var/www/sharli/application/LinkFilter.php(79): LinkFilter->filterTags('ideas ', false, false)
#2 /var/www/sharli/application/LinkDB.php(433): LinkFilter->filter('tags', 'ideas ', false, false)
#3 /var/www/sharli/index.php(1598): LinkDB->filterSearch(Array, false, false)
#4 /var/www/sharli/index.php(730): buildLinkList(Object(PageBuilder), Object(LinkDB), Object(ConfigManager), Object(PluginManager))
#5 /var/www/sharli/index.php(1567): showLinkList(Object(PageBuilder), Object(LinkDB), Object(ConfigManager), Object(PluginManager))
#6 /var/www/sharli/index.php(2188): renderPage(Object(ConfigManager), Object(PluginManager))
#7 {main}
  thrown in /var/www/sharli/application/LinkFilter.php on line 351" while reading response header from upstream, client: 117.99.186.95, server: bookmarks.abc.xyz, request: "GET /?searchtags=ideas+ HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "bookmarks.abc.xyz", referrer: "http://bookmarks.abc.xyz/?"
```

**Comment by ankitml** [comment]
Solved it by installing 
```php-mbstring```
